version: '3.8'

services:
  djmeet_api:
    image: djmeet_api:latest
    container_name: djmeet_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/workspace:z
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      djmeet_db:
        condition: service_started
    restart: on-failure

  djmeet_db:
    image: postgres:15.4-alpine
    container_name: djmeet_db
    volumes:
      - djmeet_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=djmeet-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5435:5432'

volumes:
  djmeet_data:
