# Generated by Django 4.2.5 on 2023-09-09 22:13

import apps.server.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=apps.server.utils.upload.icon_path),
        ),
    ]
