# Generated by Django 4.2.5 on 2023-09-09 22:26

import apps.server.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_server_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to=apps.server.utils.upload.banner_path),
        ),
    ]
