version: '3.8'
services:
  vscode:
    user: user
    image: djmeet_api:latest
    container_name: djmeet_vscode
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
